name: swim
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  shared_preferences: ^2.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.1
  path_provider: ^2.0.3
  google_fonts: ^6.1.0
  marquee: ^2.2.3
  video_player: ^2.7.0
  lottie: ^3.1.0

  table_calendar: ^3.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.0
  image_picker: ^1.0.4
  firebase_storage: ^12.4.7
  share_plus: ^7.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/ppppig.mp3
    - assets/Take your marks.mp3
    - assets/지금부터 쉬는 시간 입니다.mp3
    - assets/훈련 종료음.mp3
    - assets/images/z_top_logo.png
    - assets/images/111.png
    - assets/images/S.png
    - assets/icons/google_logo.png
    - assets/icons/google_logo2.png
    - assets/icons/apple_logo.png
    - assets/icons/apple_logo2.png
    - assets/videos/swim.mp4
    - assets/animations/swimming_starter.json

  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/myfont.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/S.png"



l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
