// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKqrIpPTpOuUEVvyvr5UZnmKlT15tJGI',
    appId: '1:191069660562:web:50c41d6eab52ef88e00d4b',
    messagingSenderId: '191069660562',
    projectId: 'zeroontop-88ce3',
    authDomain: 'zeroontop-88ce3.firebaseapp.com',
    storageBucket: 'zeroontop-88ce3.firebasestorage.app',
    measurementId: 'G-TX3DJ4J3N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ph_91aooYVODK9KWYf5F-T5J6iUvM90',
    appId: '1:191069660562:android:377eb6d5889690c2e00d4b',
    messagingSenderId: '191069660562',
    projectId: 'zeroontop-88ce3',
    storageBucket: 'zeroontop-88ce3.firebasestorage.app',
  );

  // 🔥 새로 추가된 iOS 설정 (스크린샷 정보 기반)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAorUDG4WhmiU7NyQ64xJw-VZbixcRDp0k',
    appId: '1:191069660562:ios:7cfefa25d1196a29e00d4b', // 스크린샷의 앱 ID
    messagingSenderId: '191069660562',
    projectId: 'zeroontop-88ce3',
    storageBucket: 'zeroontop-88ce3.firebasestorage.app',
    iosBundleId: 'com.zalmuk.swim', // 스크린샷의 번들 ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAorUDG4WhmiU7NyQ64xJw-VZbixcRDp0k',
    appId: '1:191069660562:ios:7cfefa25d1196a29e00d4b', // iOS와 동일
    messagingSenderId: '191069660562',
    projectId: 'zeroontop-88ce3',
    storageBucket: 'zeroontop-88ce3.firebasestorage.app',
    iosBundleId: 'com.zalmuk.swim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOKqrIpPTpOuUEVvyvr5UZnmKlT15tJGI',
    appId: '1:191069660562:web:9a8481c2869a3173e00d4b',
    messagingSenderId: '191069660562',
    projectId: 'zeroontop-88ce3',
    authDomain: 'zeroontop-88ce3.firebaseapp.com',
    storageBucket: 'zeroontop-88ce3.firebasestorage.app',
    measurementId: 'G-JZSTEYYQ43',
  );
}
